package epaw.lab4.util;

import java.io.BufferedReader;
import java.io.FileReader;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.sql.*;
import java.util.stream.Collectors;

public class DBManager {

	private static DBManager instance;
	private Connection connection = null;
	private static final String DB_FILE = "lab4.db";

	private DBManager() {
		try {
			// SQLite connection
			Class.forName("org.sqlite.JDBC");
			Files.deleteIfExists(Paths.get(DB_FILE));
			connection = DriverManager.getConnection("jdbc:sqlite:" + DB_FILE);

			// Enable foreign keys in SQLite
			try (Statement stmt = connection.createStatement()) {
				stmt.execute("PRAGMA foreign_keys = ON;");
			}

			initDatabase();
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	public static synchronized DBManager getInstance() {
		if (instance == null) {
			instance = new DBManager();
		}
		return instance;
	}

	private void initDatabase() throws Exception {
		String schemaPath = "DB.txt";
		try (BufferedReader reader = new BufferedReader(new FileReader(schemaPath))) {
			String schema = reader.lines().collect(Collectors.joining("\n"));
			try (Statement stmt = connection.createStatement()) {
				StringBuilder buf = new StringBuilder();
				boolean inStr = false;
				for (int i = 0; i < schema.length(); i++) {
					char c = schema.charAt(i);
					// Skip -- line comments (only outside string literals)
					if (!inStr && c == '-' && i + 1 < schema.length() && schema.charAt(i + 1) == '-') {
						while (i < schema.length() && schema.charAt(i) != '\n') i++;
						continue;
					}
					if (c == '\'' && !inStr) {
						inStr = true;
					} else if (c == '\'' && inStr) {
						// '' is an escaped single quote inside a string
						if (i + 1 < schema.length() && schema.charAt(i + 1) == '\'') {
							buf.append(c);
							i++;
						} else {
							inStr = false;
						}
					} else if (c == ';' && !inStr) {
						String sql = buf.toString().trim();
						if (!sql.isEmpty()) stmt.execute(sql);
						buf = new StringBuilder();
						continue;
					}
					buf.append(c);
				}
				String last = buf.toString().trim();
				if (!last.isEmpty()) stmt.execute(last);
			}
		}
	}

	public PreparedStatement prepareStatement(String query) throws SQLException {
		return connection.prepareStatement(query);
	}

	public PreparedStatement prepareStatement(String query, int autoGeneratedKeys) throws SQLException {
		return connection.prepareStatement(query, autoGeneratedKeys);
	}

	public void close() {
		try {
			if (connection != null && !connection.isClosed()) {
				connection.close();
			}
		} catch (SQLException e) {
			e.printStackTrace();
		}
	}
}